import { Router } from 'express';
import adminRoutes from './adminRoutes.js';
import academicYearRoutes from './academicYearRoutes.js';
import aiRoutes from './aiRoutes.js';
import announcementRoutes from './announcementRoutes.js';
import authRoutes from './authRoutes.js';
import curriculumRoutes from './curriculumRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import departmentRoutes from './departmentRoutes.js';
import fileRoutes from './fileRoutes.js';
import materialRoutes from './materialRoutes.js';
import notificationPreferenceRoutes from './notificationPreferenceRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import performanceRoutes from './performanceRoutes.js';
import profileRoutes from './profileRoutes.js';
import quizRoutes from './quizRoutes.js';
import reportRoutes from './reportRoutes.js';
import resultRoutes from './resultRoutes.js';
import searchRoutes from './searchRoutes.js';
import securityRoutes from './securityRoutes.js';
import settingsRoutes from './settingsRoutes.js';
import studentQuizRoutes from './studentQuizRoutes.js';
import studentRoutes from './studentRoutes.js';
import teacherAnalyticsRoutes from './teacherAnalyticsRoutes.js';
import superAdminRoutes from './superAdminRoutes.js';
import teacherRoutes from './teacherRoutes.js';
import timezoneRoutes from './timezoneRoutes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/notifications', notificationRoutes);
router.use('/announcements', announcementRoutes);
router.use('/notification-preferences', notificationPreferenceRoutes);
router.use('/profile', profileRoutes);
router.use('/search', searchRoutes);
router.use('/security', securityRoutes);
router.use('/performance', performanceRoutes);
router.use('/files', fileRoutes);
router.use('/ai', aiRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/departments', departmentRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/admin', adminRoutes);
router.use('/teacher', teacherAnalyticsRoutes);
router.use('/teacher', teacherRoutes);
router.use('/student/quiz', studentQuizRoutes);
router.use('/student', studentRoutes);
router.use('/curriculum', curriculumRoutes);
router.use('/materials', materialRoutes);
router.use('/quiz', quizRoutes);
router.use('/results', resultRoutes);
router.use('/reports', reportRoutes);
router.use('/settings', settingsRoutes);
router.use('/academic-years', academicYearRoutes);
router.use('/timezones', timezoneRoutes);

export default router;
