CREATE TABLE IF NOT EXISTS ai_usage_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE,
  provider VARCHAR(60) NOT NULL,
  model VARCHAR(120) NOT NULL,
  teacher_id BIGINT UNSIGNED NULL,
  curriculum_id BIGINT UNSIGNED NULL,
  course_id BIGINT UNSIGNED NULL,
  subject VARCHAR(180) NULL,
  topic VARCHAR(180) NULL,
  week_no INT UNSIGNED NULL,
  prompt_id VARCHAR(120) NULL,
  started_at TIMESTAMP NULL,
  ended_at TIMESTAMP NULL,
  duration_ms INT UNSIGNED NULL,
  prompt_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  completion_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  total_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  estimated_cost DECIMAL(12, 6) NOT NULL DEFAULT 0,
  questions_generated INT UNSIGNED NOT NULL DEFAULT 0,
  questions_rejected INT UNSIGNED NOT NULL DEFAULT 0,
  questions_saved INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('success', 'failed') NOT NULL DEFAULT 'success',
  error_message VARCHAR(255) NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_usage_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_usage_curriculum FOREIGN KEY (curriculum_id) REFERENCES curriculums(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_usage_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL,
  INDEX idx_ai_usage_provider_created (provider, created_at),
  INDEX idx_ai_usage_teacher_created (teacher_id, created_at)
);
