import {
  FiBarChart2,
  FiBell,
  FiBookOpen,
  FiClipboard,
  FiClock,
  FiCpu,
  FiFileText,
  FiFolder,
  FiHome,
  FiKey,
  FiLayers,
  FiLogOut,
  FiMonitor,
  FiSearch,
  FiSettings,
  FiShield,
  FiUser,
  FiUsers,
  FiZap,
} from 'react-icons/fi';
import { USER_ROLES } from './constants';

export const sidebarNavigation = {
  [USER_ROLES.SUPER_ADMIN]: [
    { label: 'Dashboard', path: '/super-admin/dashboard', icon: FiHome },
    { label: 'Admin Management', path: '/super-admin/admins', icon: FiUsers },
    { label: 'User Overview', path: '/super-admin/users', icon: FiUser },
    { label: 'Curriculum Overview', path: '/super-admin/curriculums', icon: FiLayers },
    { label: 'Reports', path: '/super-admin/reports', icon: FiBarChart2 },
    { label: 'AI Monitoring', path: '/super-admin/ai-monitoring', icon: FiCpu },
    { label: 'Global Search', path: '/search', icon: FiSearch },
    { label: 'File Manager', path: '/files', icon: FiFolder },
    { label: 'Search Analytics', path: '/super-admin/search-analytics', icon: FiSearch },
    { label: 'Security Center', path: '/super-admin/security', icon: FiShield },
    { label: 'Performance', path: '/super-admin/performance', icon: FiZap },
    { label: 'Notifications', path: '/notifications', icon: FiBell },
    { label: 'Announcements', path: '/announcements', icon: FiClock },
    { label: 'Audit Logs', path: '/super-admin/audit-logs', icon: FiClock },
    { label: 'System Settings', path: '/super-admin/settings', icon: FiSettings },
    { label: 'Profile', path: '/super-admin/profile', icon: FiUser },
    { label: 'Security', path: '/super-admin/profile', icon: FiKey },
    { label: 'Preferences', path: '/settings', icon: FiSettings },
    { label: 'Login History', path: '/settings', icon: FiClock },
    { label: 'Connected Sessions', path: '/super-admin/profile', icon: FiMonitor },
    { label: 'Notification Settings', path: '/notification-preferences', icon: FiBell },
    { label: 'Logout', path: '/login', icon: FiLogOut, action: 'logout' },
  ],
  [USER_ROLES.ADMIN]: [
    { label: 'Dashboard', path: '/admin/dashboard', icon: FiHome },
    { label: 'Teacher Management', path: '/admin/teachers', icon: FiUsers },
    { label: 'Student Management', path: '/admin/students', icon: FiUser },
    { label: 'Department Management', path: '/admin/departments', icon: FiLayers },
    { label: 'Curriculum Management', path: '/admin/curriculums', icon: FiLayers },
    { label: 'Learning Materials', path: '/admin/materials', icon: FiBookOpen },
    { label: 'Reports', path: '/admin/reports', icon: FiBarChart2 },
    { label: 'Global Search', path: '/search', icon: FiSearch },
    { label: 'File Manager', path: '/files', icon: FiFolder },
    { label: 'Notifications', path: '/notifications', icon: FiBell },
    { label: 'Announcements', path: '/announcements', icon: FiClock },
    { label: 'Profile', path: '/admin/profile', icon: FiUser },
    { label: 'Settings', path: '/admin/settings', icon: FiSettings },
    { label: 'Security', path: '/admin/profile', icon: FiKey },
    { label: 'Preferences', path: '/admin/settings', icon: FiSettings },
    { label: 'Login History', path: '/admin/settings', icon: FiClock },
    { label: 'Connected Sessions', path: '/admin/profile', icon: FiMonitor },
    { label: 'Notification Settings', path: '/notification-preferences', icon: FiBell },
    { label: 'Logout', path: '/login', icon: FiLogOut, action: 'logout' },
  ],
  [USER_ROLES.TEACHER]: [
    { label: 'Dashboard', path: '/teacher/dashboard', icon: FiHome },
    { label: 'My Students', path: '/teacher/students', icon: FiUsers },
    { label: 'Learning Materials', path: '/teacher/materials', icon: FiBookOpen },
    { label: 'Videos', path: '/teacher/videos', icon: FiFileText },
    { label: 'Teacher Notes', path: '/teacher/notes', icon: FiClipboard },
    { label: 'Announcements', path: '/teacher/announcements', icon: FiClock },
    { label: 'Notification Center', path: '/notifications', icon: FiBell },
    { label: 'Global Search', path: '/search', icon: FiSearch },
    { label: 'File Manager', path: '/files', icon: FiFolder },
    { label: 'Weekly Plan', path: '/teacher/weekly-plan', icon: FiClipboard },
    { label: 'Completed Topics', path: '/teacher/completed-topics', icon: FiLayers },
    { label: 'Quiz Analytics', path: '/teacher/quiz-analytics', icon: FiBarChart2 },
    { label: 'Reports', path: '/teacher/reports', icon: FiBarChart2 },
    { label: 'Student Marks', path: '/teacher/marks', icon: FiBarChart2 },
    { label: 'Profile', path: '/teacher/profile', icon: FiUser },
    { label: 'Settings', path: '/teacher/settings', icon: FiSettings },
    { label: 'Security', path: '/teacher/profile', icon: FiKey },
    { label: 'Preferences', path: '/teacher/settings', icon: FiSettings },
    { label: 'Login History', path: '/teacher/settings', icon: FiClock },
    { label: 'Connected Sessions', path: '/teacher/profile', icon: FiMonitor },
    { label: 'Notification Settings', path: '/notification-preferences', icon: FiBell },
    { label: 'Logout', path: '/login', icon: FiLogOut, action: 'logout' },
  ],
  [USER_ROLES.STUDENT]: [
    { label: 'Dashboard', path: '/student/dashboard', icon: FiHome },
    { label: 'My Curriculum', path: '/student/curriculum', icon: FiLayers },
    { label: 'Learning Materials', path: '/student/materials', icon: FiBookOpen },
    { label: 'Videos', path: '/student/videos', icon: FiFileText },
    { label: 'Teacher Notes', path: '/student/notes', icon: FiClipboard },
    { label: 'Announcements', path: '/student/announcements', icon: FiClock },
    { label: 'Notification Center', path: '/notifications', icon: FiBell },
    { label: 'Global Search', path: '/search', icon: FiSearch },
    { label: 'My Files', path: '/files', icon: FiFolder },
    { label: 'Assignments', path: '/student/assignments', icon: FiClipboard },
    { label: 'Upload Video', path: '/student/upload-video', icon: FiFileText },
    { label: 'AI Quiz', path: '/student/ai-quiz', icon: FiBarChart2 },
    { label: 'Quiz History', path: '/student/quiz-history', icon: FiClock },
    { label: 'Results', path: '/student/results', icon: FiBarChart2 },
    { label: 'Reports', path: '/student/reports', icon: FiBarChart2 },
    { label: 'Profile', path: '/student/profile', icon: FiUser },
    { label: 'Settings', path: '/student/settings', icon: FiSettings },
    { label: 'Security', path: '/student/profile', icon: FiKey },
    { label: 'Preferences', path: '/student/settings', icon: FiSettings },
    { label: 'Login History', path: '/student/settings', icon: FiClock },
    { label: 'Connected Sessions', path: '/student/profile', icon: FiMonitor },
    { label: 'Notification Settings', path: '/notification-preferences', icon: FiBell },
    { label: 'Logout', path: '/login', icon: FiLogOut, action: 'logout' },
  ],
};
